name: CI

on:
  push:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Pack
        run: pnpm pack
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pack
          path: "*.tgz"
      - if: github.event_name == 'release'
        name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
