name: Release Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: |-
          bun install
          bun pm bin >> "$GITHUB_PATH"
      - name: Build
        run: bun run compile
      - name: Rename
        run: mv "./dist/sing" "./dist/sing-${{ runner.arch }}-${{ runner.os }}"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ runner.arch }}-${{ runner.os }}
          path: ./dist/
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: bin-*
          merge-multiple: true
      - name: Release
        uses: liblaf/actions/release@main
        with:
          clobber: true
          files: ./dist/*
          prerelease: true
          tag: dev
