name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
